export {default as StarterView} from './StarterView'
export {default as MainView} from './MainView'
export {default as Sidebar} from './Sidebar'
export {default as DishView} from './DishView'
export {default as TotalMenu} from './TotalMenu'
export {default as Presentation} from './Presentation'
export {default as Dish} from './Dish'
